version: "3"

services:
    webserver:
        build: .docker/webserver
        container_name: "webserver"
        ports: 
            - "8009:80"
        volumes:
            - ./www:/var/www/html/
        networks:
            - default
                    
    mysql:
        build: .docker/mysql
        container_name: "mysql"
        ports:
            - 3306:3306
        volumes:
            - ${MYSQL_DATA_DIR-.docker/data/mysql}:/var/lib/mysql
            - ${MYSQL_LOG_DIR-.docker/logs/mysql}:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: demo
            MYSQL_USER: user
            MYSQL_PASSWORD: password

    phpmyadmin:
        build: .docker/phpmyadmin
        container_name: "phpmyadmin"
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - '8010:80'
        volumes:
            - .docker/sessions


